# numpy is a linear algebra library for python, almost all of the libraries in the PyData ecosystem rely on numpy 
## you can install it ```conda install numpy``` or ```pip install numpy``` depending on package manager you are using

In [1]:
# importing the library
import numpy as np

In [2]:
# we are gonna deal with numpy arrays which comes in two flavors [Vectors <1-d arrays> , Matrices <2-d arrays>]
# NOTE: a matrix can have one row or one column.

In [3]:
# creating a numpy array from a list
lisa = [1,2,3]
arr = np.array(lisa)
arr # this is gonna return an one dimensional array

array([1, 2, 3])

In [4]:
lisa = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(lisa)
arr # this is gonna return a two dimensional array (rows and columns)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# GENETAING NUMPY ARRAY
# np.arange(start, stop, step) for a 2d array <step is optional> or np.arange(number of vlaues) for a 1d array
np.arange(0,101,2) # this is gonna return all the even numbers from 0 to 100

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [6]:
# np.zeros((no. rows, no. columns))
np.zeros((5,4)) # this is gonna return an array of zeros with the shape (5,4) meaning 5 rows and 4 columns.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# np.ones((no. rows, no. columns))
np.ones((3,4)) # this is gonna return an array of zeros with the shape (3,4) meaning 3 rows and 4 columns.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# and you can manipulate the ones array as follow
np.ones((3,4)) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [9]:
# np.linspace(start, stop, number_of_values_wanted)
np.linspace(0,10,5) # this is gonna return a 5 values equally spced within range(0,11)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
# creaing identity mtatrix
# np.eye(number_of_rows) NOTE: the number of columns equal the number of rows and with diagonal of ones
np.eye(6) # this is gonna return identity matrix of 6 c. and r.

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## RANDOM ARRAYS

In [11]:
# np.random.rand(1) for one dimensional array or np.random.rand(5,5) for multi dimensional array
# populate the array with a random samples from a uniform distribution from [0:1]
np.random.rand(6,5)

array([[0.99813562, 0.4599498 , 0.29936015, 0.9553891 , 0.76380103],
       [0.61444156, 0.95709763, 0.27023899, 0.91321087, 0.3075029 ],
       [0.05733122, 0.82598494, 0.52485095, 0.9933929 , 0.73290787],
       [0.60125797, 0.47565369, 0.7898169 , 0.02075379, 0.81716372],
       [0.64506607, 0.68459572, 0.46637014, 0.333181  , 0.33568966],
       [0.2580216 , 0.39023845, 0.78712047, 0.99617797, 0.02038963]])

In [12]:
np.random.rand(5) # for one dimensional rand array

array([0.51274264, 0.34507809, 0.30037846, 0.87367214, 0.26628996])

In [13]:
# np.random.randn(number) for 1d array or np.random.randn(shape) for 2d array
# populate the array with a standered normal distribution centered around zero 0
np.random.randn(5,6)

array([[-0.99902398,  1.30830947, -0.85258198, -0.56393159,  0.04510981,
        -1.14387869],
       [-0.36170605,  0.67447964,  0.09059523, -2.05314325,  0.42542247,
         0.89061957],
       [-0.08706653, -1.88283937, -0.93370517,  0.28906419,  2.11822771,
        -1.66071293],
       [-1.37058248,  0.43639399, -1.30698973, -0.52549205, -1.04374282,
         0.45081196],
       [ 2.78432867, -0.38946163, -0.78175609, -1.2842035 , -0.3004065 ,
         0.61817157]])

In [14]:
# np.random.randint(low, high, (shape)) this returns a random array of integers from low vlaue to a high vlaue
np.random.randint(0,100,(5,5))

array([[56, 22, 22, 31, 95],
       [35, 85, 60, 31, 29],
       [ 9, 52, 34, 75, 39],
       [73, 69,  8, 12, 60],
       [76, 74, 26, 73, 94]])

In [15]:
# USEFUL ATTRIBUTES AND METHODS FOR AN ARRAY:
arr = np.arange(25)
arr.shape # returns the shape of a function

(25,)

In [16]:
rnarr = np.random.randint(0,50,10)
rnarr

array([12, 29,  7,  5, 34, 18, 33, 13,  2, 10])

In [17]:
# reshaping an array
arr.reshape(5,5) # NOTE: the number of rows times the number of columns should equal the total number of elements in the array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
print(arr.max()) # return the max value of an array
print(arr.min()) # return the min value of an array
print(arr.argmax()) # return the location of the max vlaue fo an array
print(arr.argmin()) # return the location of the min value of an array

24
0
24
0


In [19]:
"minimum value = {}, index of minimum value = {}, min value from the the index = {}".format(rnarr.min(), rnarr.argmin(), rnarr[2])

'minimum value = 2, index of minimum value = 8, min value from the the index = 7'

In [20]:
rnarr.dtype # this returns the actual data type in your array

dtype('int64')

## Numpy idexing and selection

In [22]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr[2] # getting the value by using the index

2

In [25]:
# using slice notaion to get values in a range [start_index: stop_index]
arr[2:6], arr[:6], arr[5:]

(array([2, 3, 4, 5]),
 array([0, 1, 2, 3, 4, 5]),
 array([ 5,  6,  7,  8,  9, 10]))

In [28]:
# one of the main differences between a python list and numpy array is that the array have the ability to broadcast
arr[0:5] = 100 # changing all the values from index 0 to index 4 with 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [29]:
arr = np.arange(0,11) # recreating the array
slice_of_arr = arr[0:5]
slice_of_arr[:] = 99 # broad casting all the values in the slice_of_arr
slice_of_arr , arr # notice that the slice_of_arr is just a view of the arr and any change applied
# to slice of arr is also applied to the original arr array, this is to avoid memory issues when dealing with
# large arrays.

(array([99, 99, 99, 99, 99]),
 array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10]))

In [30]:
# to specifically indicate that you want a copy from an array
arr_copy = arr.copy()
arr_copy[:] = 55
arr_copy, arr # notice that changes on arr_copy are not applied on the original arr array

(array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55]),
 array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10]))

In [34]:
np.random.seed(100) # this is gonna make the randomly generated arrays stay the same each time program runs.
arr = np.random.randint(0,26, (5,5)) # creating a 2d array
arr

array([[ 8, 24,  3,  7, 23],
       [15, 16, 10, 20,  2],
       [21,  2,  2, 14,  2],
       [17, 16, 24, 15,  4],
       [11, 16,  9, 22,  2]])

In [36]:
# arr[row][column]: double bracket notation <or> arr[row, column]: comma notation
arr[0][1], arr[0,1] # both should give the element 24

(24, 24)

In [39]:
# slice notation: getting a slice from an array
arr[:2, 2:] # grap every row from row 0 to row 1 (2 excluded) and every columns from column 2 till the end.

array([[ 3,  7, 23],
       [10, 20,  2]])

In [40]:
# some exercise on slicing arrays
tara = np.random.randint(1,1001,(5,200)) # 2d array with 5 rows and 200 columns
tara

array([[668, 877, 901, 416, 898, 142, 758, 724, 613,   5, 604, 956, 836,
        136,  50, 432, 706, 318, 783, 696, 968, 764, 337,   3, 890, 618,
        479, 404, 995,  64, 182, 284, 825, 239, 370, 927, 945, 304, 680,
        878, 807, 173, 275, 193, 953, 931, 438, 715, 274, 585, 526, 619,
         31,  18,  54,  69, 947, 489, 348, 476, 980, 694, 847,   1,  14,
        186, 461, 363, 132, 583, 644, 213, 720, 395, 216, 503, 496, 957,
        644, 874, 177, 181, 812,  37, 774, 840,  39, 215,  95, 739, 171,
        853,  96, 627, 750, 632,  77, 802, 315, 103, 939, 407, 257, 763,
        696, 227, 916, 822, 197, 447, 819, 453, 420, 408, 766, 522, 945,
        497, 790, 410, 439, 263, 678, 871, 123, 629, 187, 296, 620, 735,
        820, 287, 890, 579, 244, 921, 440, 274, 814, 486,  90, 430, 804,
         17, 525, 855, 467, 622,  68, 221, 224, 789, 139, 777, 474, 713,
        415, 909, 659, 350, 888, 605, 557, 246,  58, 384, 769, 586, 745,
        695, 989, 835, 657, 390, 436, 347,  35, 452

In [41]:
tara[:2, :5] # rows up to 2 and columns up to 5

array([[668, 877, 901, 416, 898],
       [131, 216, 146, 238, 731]])

In [43]:
tara[0:6, 190:201].reshape(50) # reshaping a 2d slice array to 1d slice array

array([478, 443, 797, 979, 723, 648, 479, 515, 576, 882, 358, 203, 444,
        12, 625, 305, 903, 987, 658, 362,   2, 648, 320, 121,  48, 370,
       873, 499, 442, 506, 663, 924,  56, 131, 880,  21, 384, 996, 431,
        59, 389, 283, 573, 956, 612, 987, 325, 664, 685, 921])

## Conditional Selection

In [44]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
bool_arr = arr > 5 # this gives true or false for each value in the array based on the condition (arr > 5)
bool_arr # then you can use this boolean array for the conditional selection

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
arr[bool_arr] # this is gonna return all the array elements greater than 5

array([ 6,  7,  8,  9, 10])

In [50]:
# instead of doing this on two steps we can do this on one step: arr[conditional statement]
arr[arr>5], arr[arr<3]

(array([ 6,  7,  8,  9, 10]), array([1, 2]))

# Numpy operations
### 1- array with array
### 2- array with scalars
### 3-universal array fnctions

In [51]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
# using simple arthmatic signs
arr + arr # adding two array (here each number is doubled)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [53]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
arr* arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [55]:
# scalars 
arr * 100 # adds or do any operation on all the array elements

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [56]:
# however numpy will issue warning in case of some arithmatic operations
arr / arr # here nan is given as "0/0" is not a known number

/home/nemo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [58]:
1 / arr # warning as "1/0" equals infinity

/home/nemo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [59]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [60]:
np.sqrt(arr) # the root of every thing in the array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [61]:
np.max(arr), arr.max()

(10, 10)

In [62]:
np.log(arr) # note that the log(0) = -inf

/home/nemo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

### universal array functions documentations:
[here you can find more information about universal functions](docs.scipy.org/doc/numpy/reference/ufuncs.html)